# Generated by Django 3.0.3 on 2020-02-13 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=150)),
                ('user_name', models.CharField(max_length=20)),
                ('assigned_user', models.CharField(max_length=20)),
                ('completed_user', models.CharField(max_length=20)),
                ('ticket_status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Invalid', 'Invalid')], default='New', max_length=15)),
            ],
        ),
    ]
