# Generated by Django 3.0.3 on 2020-02-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_ticket', '0002_auto_20200213_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerticket',
            name='ticket_status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Invalid', 'Invalid')], max_length=15),
        ),
    ]
