# Generated by Django 3.0.3 on 2020-02-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_ticket', '0003_auto_20200213_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerticket',
            name='assigned_user',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='trackerticket',
            name='completed_user',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='trackerticket',
            name='user_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
