# Generated by Django 3.0.3 on 2020-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_ticket', '0006_auto_20200213_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerticket',
            name='ticket_status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Invalid', 'Invalid')], default='New', max_length=15, null=True),
        ),
    ]
